// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzoVb92BL2CA0b40V7FdcJQ-fSJoOCk0',
    appId: '1:977827779090:web:584b162b3d0d5b733c3ecb',
    messagingSenderId: '977827779090',
    projectId: 'e-shop-edf51',
    authDomain: 'e-shop-edf51.firebaseapp.com',
    storageBucket: 'e-shop-edf51.appspot.com',
    measurementId: 'G-CQM9FE4Z0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8w1LzUFBuculQnTh6gTXO31vR76J-8p0',
    appId: '1:977827779090:android:7529161fb9c474e63c3ecb',
    messagingSenderId: '977827779090',
    projectId: 'e-shop-edf51',
    storageBucket: 'e-shop-edf51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQY3MKZGsGstOINppc2gY7-l0lgx3Hzd4',
    appId: '1:977827779090:ios:a475efa424fd32c83c3ecb',
    messagingSenderId: '977827779090',
    projectId: 'e-shop-edf51',
    storageBucket: 'e-shop-edf51.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQY3MKZGsGstOINppc2gY7-l0lgx3Hzd4',
    appId: '1:977827779090:ios:a475efa424fd32c83c3ecb',
    messagingSenderId: '977827779090',
    projectId: 'e-shop-edf51',
    storageBucket: 'e-shop-edf51.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzoVb92BL2CA0b40V7FdcJQ-fSJoOCk0',
    appId: '1:977827779090:web:3908b229576cc1aa3c3ecb',
    messagingSenderId: '977827779090',
    projectId: 'e-shop-edf51',
    authDomain: 'e-shop-edf51.firebaseapp.com',
    storageBucket: 'e-shop-edf51.appspot.com',
    measurementId: 'G-3T2YZFQZM1',
  );
}
